function [oa, pa, K, CM] = USFE_LPP(HSI, Tr, Te, dim, Trees)
[nx,ny,nz]=size(HSI);
data=reshape(HSI,nx*ny,nz);
[mappedX, mapping] = lpp(data, dim);
FE_lpp=reshape(mappedX,nx,ny,dim);
[acc_Mean,acc_std,CM]=RF_ntimes_overal(FE_lpp,Tr,Te,Trees);
pa=acc_Mean(1:dim,1);
oa=acc_Mean(dim+2,1);
K=acc_Mean(dim+3,1);